name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'gcloud'
    
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
    
    - name: Build and push Docker image
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: flask-todo
        region: asia-northeast1
        source: .
        env_vars: |
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=todo
          GCS_BUCKET_NAME=todo-app-images
        flags: |
          --allow-unauthenticated
          --platform=managed
          --cpu=1
          --memory=512Mi
          --min-instances=0
          --max-instances=10